# Project
mod_name=Test Mod
mod_author=possible_triangle
mod_id=test_mod
mod_version=0.0.0-1.21.x-dev
release_type=alpha

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.1

# Forge
neoforge_version=21.1.219
kotlin_forge_version=5.11.0

# Publishing
repository=pssbletrngle/testmod
maven_group=com.possible-triangle
modrinth_project_id=t7zT6WfX
curseforge_project_id=870454