# Project
mod_name=Test Mod
mod_author=possible_triangle
mod_id=test_mod
mod_version=0.0.0-26.1.x-dev
release_type=alpha

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft
minecraft_version=26.1.2

# Fabric
fabric_api_version=0.149.1+26.1.2
fabric_loader_version=0.19.2
kotlin_fabric_version=1.13.11+kotlin.2.3.21

# Publishing
repository=pssbletrngle/testmod
maven_group=com.possible-triangle
modrinth_project_id=t7zT6WfX
curseforge_project_id=870454