# Project
mod_name=Test Mod
mod_author=possible_triangle
mod_id=test_mod
mod_version=0.0.0-26.1.x-dev
release_type=alpha

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft
minecraft_version=26.1.2

# Forge
neoforge_version=26.1.2.43-beta
kotlin_forge_version=6.2.0

# Publishing
repository=pssbletrngle/testmod
maven_group=com.possible-triangle
modrinth_project_id=t7zT6WfX
curseforge_project_id=870454
