name: Trigger Test

on:
  schedule:
    - cron: "10 4 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-test]

env:
  CI: true

jobs:
  trigger:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        setup:
          - key: architectury
            version: 1.20.x
          - key: architectury
            version: 1.21.x
          - key: common
            version: 1.20.x
          - key: common
            version: 1.21.x
          - key: neoforge
            version: 1.21.x
          - key: forge
            version: 1.20.x
          - key: fabric
            version: 1.21.x
          - key: fabric
            version: 1.20.x
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main/${{ matrix.setup.key }}/${{ matrix.setup.version }}
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Test
        run: ./gradlew build check publish
