name: Trigger Release

on:
  schedule:
    - cron: "30 4 * * 0,3"
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-releases]

jobs:
  trigger:
    strategy:
      matrix:
        type: [architectury, common, fabric, neoforge]
        version: [1.20.x, 1.21.x, 26.1.x]
        include:
          - type: forge
            version: 1.20.x
        exclude:
          - type: neoforge
            version: 1.20.x
          - type: architectury
            version: 26.1.x
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ matrix.type }} 1.0.${{ github.run_number }} (${{ matrix.version }})
          tag_name: 1.0.${{ github.run_number }}-${{ matrix.version }}-${{ matrix.type }}
          body: "this is an automatic test release"
          target_commitish: main/${{ matrix.type }}/${{ matrix.version }}
          token: ${{ secrets.TRIGGER_TOKEN }}
