name: Trigger Test

on:
  schedule:
    - cron: "10 4 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-test]

env:
  CI: true

jobs:
  trigger:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        type: [architectury, common, fabric, neoforge]
        version: [1.20.x, 1.21.x, 26.1.x]
        include:
          - type: forge
            version: 1.20.x
        exclude:
          - type: neoforge
            version: 1.20.x
          - type: architectury
            version: 26.1.x
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main/${{ matrix.type }}/${{ matrix.version }}
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 26
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Test
        run: ./gradlew build check publish
